print("lee is working hardly ......")
print("lee is working hardly .....")
print("lee is working hardly ....")
print("lee is working hardly ...")
print("lee is working hardly ..")
print("lee is working hardly .")